Repository Evandro18/React-Calendar, pull requests merged in 2020-04, with the labels that each got.

#1 Feat/selection types
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/Button/index.js
  src/Button/styles.css
  src/CalendarDays.js
  src/CalendarHeader.js
  src/MonthsSelect.js
  src/ParseDate.js
  src/Years.js
  src/contants.js
  src/css/CalendarDays.css
  src/css/CalendarMonth.css
  src/css/styles.css
  src/getDaysInMonth.js
  src/index.js
Labels: feature

#2 Feat/selection types
  package.json
  src/App.js
  src/CalendarDays.js
  src/CalendarHeader.js
  src/MonthsSelect.js
  src/ParseDate.js
  src/contants.js
  src/css/CalendarDays.css
  src/css/CalendarMonth.css
  src/css/styles.css
  src/index.js
Labels: bug, help wanted

#4 refact(components): organized folder structure
  src/components/Button/index.js
  src/components/Button/styles.css
  src/components/Calendar/CalendarDays/index.js
  src/components/Calendar/Header/index.js
  src/components/Calendar/MonthsSelect/index.js
  src/components/Calendar/YearsSelect/index.js
  src/components/Calendar/index.js
  src/index.js
  src/utils/ParseDate.js
  src/utils/contants.js
  src/utils/getDaysInMonth.js
Labels: refactor

#5 Develop
  src/components/Button/index.js
  src/components/Button/styles.css
  src/components/Calendar/CalendarDays/index.js
  src/components/Calendar/Header/index.js
  src/components/Calendar/MonthsSelect/index.js
  src/components/Calendar/YearsSelect/index.js
  src/components/Calendar/index.js
  src/index.js
  src/utils/ParseDate.js
  src/utils/contants.js
  src/utils/getDaysInMonth.js
Labels: refactor

#6 Feat/year select
  src/components/Calendar/Header/index.js
  src/components/Calendar/YearSelect/index.js
  src/components/Calendar/YearSelect/style.css
  src/components/Calendar/YearsSelect/index.js
  src/components/Calendar/index.js
  src/utils/constants.js
Labels: feature

#7 Feat/add rollup bundler
  .gitignore
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  package.json
  rollup.config.js
  src/components/Calendar/index.js
  src/components/Input/index.js
  src/components/Input/inputpicker.css
  src/css/styles.css
  src/example/.env
  src/example/.gitignore
  src/example/README.md
  src/example/config/env.js
  src/example/config/getHttpsConfig.js
  src/example/config/jest/cssTransform.js
  src/example/config/jest/fileTransform.js
  src/example/config/modules.js
  src/example/config/paths.js
  src/example/config/pnpTs.js
  src/example/config/webpack.config.js
  src/example/config/webpackDevServer.config.js
  src/example/package.json
  src/example/public/favicon.ico
  src/example/public/index.html
  src/example/public/logo192.png
  src/example/public/logo512.png
  src/example/public/manifest.json
  src/example/public/robots.txt
  src/example/scripts/build.js
  src/example/scripts/start.js
  src/example/scripts/test.js
  src/example/src/App.js
  src/example/src/index.js
  src/icons/Calendar.js
  src/index.js
  src/utils/ParseDate.js
Labels: feature

#9 fix(range-picker): fix layout input and select dates
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Calendar/index.js
  src/components/Input/index.js
  src/components/Input/inputpicker.css
  src/css/CalendarDays.css
Labels: bug

#11 fix(days-layout): fix align day number
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/css/CalendarDays.css
Labels: bug

#12 fix(range-picker): fix font
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Calendar/index.js
  src/components/Input/index.js
  src/components/Input/inputpicker.css
  src/example/src/App.js
  src/icons/Calendar.js
  src/utils/ParseDate.js
  src/utils/constants.js
Labels: layout

#13 Fix/week day labels
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  package.json
  src/components/Calendar/index.js
  src/components/Input/index.js
  src/example/.env
Labels: bug

#14 fix(range-picker): add onclick action on input
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Input/index.js
Labels: feature

#16 feat(example): added new types
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Calendar/index.js
  src/example/src/App.js
  src/example/src/components/RadioButton/style.css
  src/example/src/style.css
Labels: feature

#17 Feat/formatter dinamic
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Input/index.js
  src/utils/ParseDate.js
Labels: feature

#18 fix(range-picker): fix pattern and fix onload checkbox
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Input/index.js
  src/example/src/App.js
  src/example/src/components/RadioButton/index.js
Labels: bug

#19 fix(button-labels): labels from parameters
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Footer/index.js
  src/components/Input/index.js
  src/example/src/App.js
Labels: bug

#20 Fix/button type
  dist/index.es.js
  dist/index.es.js.map
  dist/index.js
  dist/index.js.map
  src/components/Button/index.js
Labels: bug
